name: "Caio's website"
description: "The website contains Caio's movies."

url: "http://localhost:4000"
baseurl: "http://Caio-Ribeiro-Films"

paginate: 20 

markdown: rdiscount 
permalink: pretty 
pygments: true 
